openapi: 3.0.0
info:
  title: AntiSocialApi
  description: Documentación AntiSocialApi
  version: 1.0.0
servers:
  - url: "http://localhost:3000"
    description: Local

components:
  schemas:
    User:
      type: object
      properties: 
        nickName:
          type: string
          minLength: 3
          maxLength: 20
          example: usuario001
        email:
          type: string
          format: email
          example: usuario001@email.com
    Post:
      type: object
      properties:
        fecha:
          type: string
          format: date-time
          example: '2025-05-18T16:00:00Z'
        descripcion:
          type: string
          minLength: 5 
          maxLength: 300
          example: nuevo post
    Post_image:
      type: object
      properties:
        url:
          type: string
          example: "/images/paisaje.jfif"
    Comment:
      type: object
      properties:
        fecha:
          type: string
          format: date-time
          example: '2025-05-18T17:00:00Z'
        descripcion:
          type: string
          minLength: 1 
          maxLength: 300
          example: nuevo comentario
    Tag:
      type: object
      properties:
        descripcion:
          type: string
          minLength: 3 
          maxLength: 300
          example: nuevo tag

paths:
  /users:
    post:
      summary: Crea un usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201': 
          description: Usuario
        '400':
          description: Error al crear user

    get:
      summary: Obtener todos los usuarios
      tags: 
        - Users
      responses:
        '200':
          description: Lista de usuarios
        '500':
          description: Error interno del servidor
  
  /users/{nickName}:
    get:
      summary: Obtener un usuario por nickName
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Usuario
        '400':
          description: Error al obtener el usuario
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    patch:
      summary: Modificar un usuario por nickName
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuario
        '400':
          description: Error al modificar usuario
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un usuario por nickName
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Usuario eliminado exitosamente
        '400':
          description: Error al eliminar usuario
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
  
  /users/{nickName}/crearPost:
    post:
      summary: Crear una nueva publicacion
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201': 
          description: Post 
        '400':
          description: Error al crear la publicación
        '404':
          description: Usuario no encontrado
        '500': 
          description: Error interno del servidor
  
  /users/{nickName}/comentarPost/{postId}:
    post:
      summary: Comentar una publicación
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string
        - name: postId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201': 
          description: Comentario 
        '400':
          description: Error al comentar la publicación
        '404':
          description: Usuario o publicación no encontrado
        '500': 
          description: Error interno del servidor
  
  /users/{nickName}/posts:
    get:
      summary: Obtener las publicaciones de un usuario
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Publicaciones
        '400':
          description: Error al obtener las publicaciones
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /users/{nickName}/followers:
    get:
      summary: Obtener los seguidores de un usuario
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Seguidores
        '400':
          description: Error al obtener seguidores
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /users/{nickName}/follows:
    get:
      summary: Obtener los usuarios seguidos de un usuario
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Seguidos
        '400':
          description: Error al obtener los usuarios seguidos
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /users/{nickName}/follow/{targetNickName}:
    post:
      summary: Seguir a un usuario
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string
        - name: targetNickName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Ahora seguís a {targetNickName} 
        '400':
          description: Error al seguir al usuario | No podes seguirte a vos mismo | No podes seguir a un usuario que ya seguís
        '404':
          description: Usuario o usuario a seguir no encontrado
        '500': 
          description: Error interno del servidor

  /users/{nickName}/unfollow/{targetNickName}:
    post:
      summary: Dejar de seguir a un usuario
      tags:
        - Users
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string
        - name: targetNickName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Ya no seguís a {targetNickName} 
        '400':
          description: Error al dejar de seguir al usuario | No podes dejar seguirte a vos mismo | No seguías a {targetNickName}
        '404':
          description: Usuario o usuario a seguir no encontrado
        '500': 
          description: Error interno del servidor

  /posts:
    get:
      summary: Obtener todas las publicaciones
      tags:
        - Posts
      responses:
        '200':
          description: Publicaciones
        '404':
          description: Publicaciones no encontradas
        '500':
          description: Error interno del servidor

  /posts/{id}:
    get:
      summary: Obtener una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Publicación 
        '400':
          description: Error al obtener la publicación
        '404':
          description: Publicación no encontrada
        '500': 
          description: Error interno del servidor
    patch:
      summary: Modificar una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post 
        '400':
          description: Descripción no agregada | Error al modificar post
        '404':
          description: Publicación no encontrada
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar una publicación por id
      tags:
        - Posts
      parameters:
        - name: nickName
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Publicación eliminada exitosamente
        '400': 
          description: Error al eliminar la publicación 
        '404':
          description: Publicación no encontrada
        '500':
          description: Error interno del servidor
  
  /posts/{id}/todosLosComments:
    get:
      summary: Obtener todos los comentarios de una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Comentarios 
        '400':
          description: Error al obtener comentarios de una publicación
        '404':
          description: Publicación no encontrada
        '500': 
          description: Error interno del servidor

  /posts/{id}/commentsRecientes:
    get:
      summary: Obtener comentarios recientes de una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Comentarios recientes
        '400':
          description: Error al obtener comentarios recientes de un post
        '404':
          description: Publicación no encontrada
        '500': 
          description: Error interno del servidor

  /posts/{id}/asociar/{tagId}:
    post:
      summary: Asignar una etiqueta por id a una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Publicación 
        '400':
          description: La etiqueta ya esta asociada a la publicación | Error al asociar la etiqueta
        '404':
          description: Etiqueta o publicación no encontrada
        '500': 
          description: Error interno del servidor

  /posts/{id}/tags:
    get:
      summary: Obtener las etiquetas de una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Etiquetas de la publicación
        '400':
          description: Error al obtener las etiquetas
        '404':
          description: Publicación no encontrada
        '500': 
          description: Error interno del servidor

  /posts/{id}/post_images:
    get:
      summary: Obtener las imágenes de una publicación por id
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Imágenes de la publicación
        '400':
          description: Error al obtener las imágenes
        '404':
          description: Publicación no encontrada
        '500': 
          description: Error interno del servidor

  /tags:
    get:
      summary: Obtener todos las etiquetas
      tags:
        - Tags
      responses:
        '200':
          description: Etiquetas
        '500':
          description: Error interno del servidor
    post:
      summary: Crear una etiqueta
      tags:
        - Tags
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '201': 
          description: Etiqueta
        '400':
          description: Error al crear la etiqueta
  
  /tags/{id}:
    get:
      summary: Obtener una etiqueta por id
      tags:
        - Tags
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Etiqueta 
        '400':
          description: Error al obtener la etiqueta
        '404':
          description: Etiqueta no encontrado
        '500': 
          description: Error interno del servidor

    patch:
      summary: Modificar una etiqueta por id
      tags:
        - Tags
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200':
          description: Etiqueta 
        '400':
          description: Error al modificar la etiqueta
        '404':
          description: Etiqueta no encontrada
        '500': 
          description: Error interno del servidor
    
    delete:
      summary: Eliminar una etiqueta por id
      tags:
        - Tags
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Etiqueta eliminada exitosamente
        '400':
          description: Error al eliminar la etiqueta
        '404':
          description: Etiqueta no encontrada
        '500': 
          description: Error interno del servidor
  
  /tags/{id}/posts:
    get:
      summary: Obtener todos posts que tengan una etiqueta
      tags:
        - Tags
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Publicaciones 
        '400':
          description: Error al obtener publicaciones con la etiqueta
        '404':
          description: Etiqueta no encontrada
        '500': 
          description: Error interno del servidor

  /post_images/{postId}:
    get:
      summary: Obtener post_image por id
      tags:
        - Post_images
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Post_image
        '400':
          description: Error al obtener post_image
        '404':
          description: Post_Image no encontrado
        '500': 
          description: Error interno del servidor
    
    patch:
      summary: Modificar un post_image por id
      tags:
        - Post_images
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post_images'
      responses:
        '200':
          description: post_image 
        '400':
          description: Error al modificar post_image
        '404':
          description: Post_Image no encontrado
        '500': 
          description: Error interno del servidor
    delete:
      summary: Eliminar un post_image por id
      tags:
        - Post_images
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Post_image eliminado exitosamente
        '400':
          description: Error al eliminar Post_Image
        '404':
          description: Post_image no encontrado
        '500':
          description: Error interno del servidor

  /post_images/{idPost}:
    post:
      summary: Crear un post_image asociado a un post por idPost 
      tags:
        - Post_images
      parameters:
        - name: idPost
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        '200': 
          description: Post_image 
        '400':
          description: Error al crear Post_Image
        '404':
          description: Post_image no encontrado
        '500':
          description: Error interno del servidor

  /comments/{id}:
    get:
      summary: Obtener un comentario por id
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Comentario 
        '400': 
          description: Error al obtener el comentario
        '404':
          description: Comentario no encontrado
        '500': 
          description: Error interno del servidor
    patch:
      summary: Modificar un comment por id
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Comentario  
        '400': 
          description: Error al modificar el comentario
        '404':
          description: Comentario no encontrado
        '500': 
          description: Error interno del servidor
    delete:
      summary: Eliminar un comment por id
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Comentario eliminado exitosamente
        '400': 
          description: Error al eliminar el comentario
        '404':
          description: Comentario no encontrado
        '500': 
          description: Error interno del servidor

  